// Code generated by controller-gen. DO NOT EDIT.
package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *MemoryPolicy) DeepCopyInto(out *MemoryPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *MemoryPolicy) DeepCopy() *MemoryPolicy {
	if in == nil {
		return nil
	}
	out := new(MemoryPolicy)
	in.DeepCopyInto(out)
	return out
}
func (in *MemoryPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
func (in *MemoryPolicyList) DeepCopyInto(out *MemoryPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]MemoryPolicy, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *MemoryPolicyList) DeepCopy() *MemoryPolicyList {
	if in == nil {
		return nil
	}
	out := new(MemoryPolicyList)
	in.DeepCopyInto(out)
	return out
}
func (in *MemoryPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
func (in *MemoryPolicySpec) DeepCopyInto(out *MemoryPolicySpec) {
	*out = *in
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
}
func (in *MemoryPolicySpec) DeepCopy() *MemoryPolicySpec {
	if in == nil {
		return nil
	}
	out := new(MemoryPolicySpec)
	in.DeepCopyInto(out)
	return out
}
func (in *MemoryPolicyStatus) DeepCopyInto(out *MemoryPolicyStatus) {
	*out = *in
	if in.LastBreachTime != nil {
		out.LastBreachTime = in.LastBreachTime.DeepCopy()
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}
func (in *MemoryPolicyStatus) DeepCopy() *MemoryPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(MemoryPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
