apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentinel-operator
  namespace: sentinel-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentinel-node-monitor
  namespace: sentinel-system
